<?php if ($this->getQuote()->getFailedCalculation() || $this->getQuote()->getDcOrderId()):?>
<tr>
	<?php if ($this->getQuote()->getFailedCalculation()):?>
		<td colspan="<?php echo $this->getColspan() + 1; ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
			<?php echo $this->getTotal()->getTitle() ?>
		</td>
	<?php else:?>
		<td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
			<?php echo $this->getTotal()->getTitle() ?>
		</td>
		<td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
			<?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
		</td>
	<?php endif;?>
</tr>
<?php endif;?>