<?php if($this->isOptional()):?>
	<div class="box">
		<div class="box-title">
			<h3><?php echo $this->helper('dccharge')->__('Import Duty & Sales Taxes') ?></h3>
		</div>
		<div class="box-content">
			<form id="dc_delivery_duty_options" action="<?php echo $this->getUrl('deliverydutyoptions/deliverydutyoptions/payPalExpressChange', array('_secure'=>true)) ?>">
				<select name="delivery_duty_type" onchange="changeServiceFeeForPayPalExpress(); return false;" style="width:250px;">
					<?php foreach($this->getDeliveryDutyOptions() as $optionKey=>$optionName):?>
						<option value="<?php echo $optionKey?>" <?php if($this->getCurrentDeliveryOption()===$optionKey) echo ' selected="selected"' ?>><?php echo $optionName?></option>
					<?php endforeach;?>
				</select>
			</form>
		</div>
	</div>
<?php endif;?>
