<div class="content-header">
	<h3><?php echo $this->__('DutyCalculator Rapid Classification Tool') ?></h3>
</div>
<table width="100%">
	<colgroup>
		<col width="50%" />
		<col width="50%" />
	</colgroup>
	<tbody>
		<tr>
			<td style="padding-right: 10px;">
				<?php echo $this->getChildHtml('export');?>
			</td>
			<td style="padding-left: 10px;">
				<?php echo $this->getChildHtml('import');?>
			</td>
		</tr>
	</tbody>
</table>